FROM node:boron
WORKDIR /asimov-deploy/
COPY package.json .
ENV NODE_ENV dev

RUN npm set progress=false && \
    npm config set depth 0 && \
    npm install -g grunt-cli && \
    npm install && \
    npm cache clean

COPY . .

ENTRYPOINT [ "npm", "run" ]
CMD [ "test" ]